// Every page of the site documents one item. Order here is the order on the
// home page.
export type Doc = {
  group: "基礎" | "版面" | "區塊" | "元件"
  slug: string
  title: string
  description: string
  /** Registry item to install, if the page is about one. */
  item?: string
  /** The page's app-shell layout; doc pages default to spotlight. */
  layout?: "spotlight" | "wide"
}

export const docs: Doc[] = [
  {
    group: "基礎",
    slug: "colors",
    title: "色彩",
    description: "12 個色票：主色群青、中性灰與 3 種狀態色。",
  },
  {
    group: "版面",
    slug: "app-shell",
    title: "四角版面",
    description:
      "每個 WinLab app 的四個角，預設是麵包屑、導覽、使用者與版本、版權，也可以換成別的內容。",
    item: "app-shell",
  },
  {
    group: "版面",
    slug: "wide",
    title: "寬版面",
    description: "時段表這類格子用滿四角之間的寬度，文字和清單不用。",
    layout: "wide",
  },
  {
    group: "區塊",
    slug: "confirm-dialog",
    title: "確認對話框",
    description: "執行前先確認，執行中鎖住按鈕，完成才關閉。",
    item: "confirm-dialog",
  },
  {
    group: "區塊",
    slug: "form-dialog",
    title: "表單對話框",
    description: "短表單叫出在頁面上方，送出中鎖住欄位，完成才關閉。",
    item: "form-dialog",
  },
  {
    group: "區塊",
    slug: "empty-state",
    title: "空狀態",
    description: "清單沒有資料或搜尋沒有結果時，統一的一句話與下一步。",
    item: "empty-state",
  },
  {
    group: "區塊",
    slug: "focus",
    title: "焦點",
    description: "每頁一個大聲的地方，其他都安靜：標籤、標題與重點、一列資訊。",
    item: "focus",
  },
  {
    group: "區塊",
    slug: "avatar-stack",
    title: "頭像疊",
    description: "多個人放在一個人的位置，指到時展開。",
    item: "avatar-stack",
  },
  {
    group: "區塊",
    slug: "countdown",
    title: "倒數",
    description: "距離某個時間還有多久，到分鐘，數字會滾動。",
    item: "countdown",
  },
  {
    group: "區塊",
    slug: "expand-row",
    title: "展開列",
    description: "清單的一列原地展開細節，不換頁也不開對話框。",
    item: "expand-row",
  },
  {
    group: "區塊",
    slug: "page-header",
    title: "頁首",
    description: "頁面標題與這頁的動作按鈕。",
    item: "page-header",
  },
  {
    group: "區塊",
    slug: "list-skeleton",
    title: "清單載入",
    description: "清單和表格第一次載入時的佔位列。",
    item: "list-skeleton",
  },
  {
    group: "區塊",
    slug: "member-combobox",
    title: "選擇成員",
    description: "用姓名或信箱搜尋實驗室成員，可單選或多選。",
    item: "member-combobox",
  },
  {
    group: "區塊",
    slug: "field-list",
    title: "明細清單",
    description: "一筆資料的欄位與值，名稱在左、內容在右。",
    item: "field-list",
  },
  {
    group: "區塊",
    slug: "status-page",
    title: "狀態頁",
    description: "找不到、出錯、沒有權限時的標題與下一步。",
    item: "status-page",
  },
  {
    group: "區塊",
    slug: "date-picker",
    title: "日期選擇",
    description: "外觀跟其他欄位一樣，點開是月曆，選了就關。",
    item: "date-picker",
  },
  {
    group: "區塊",
    slug: "action-panel",
    title: "單一動作",
    description:
      "整頁只做一件事，例如開門：一顆大按鈕，執行中鎖住，成功後短暫變色。",
    item: "action-panel",
  },
  {
    group: "區塊",
    slug: "file-upload",
    title: "上傳檔案",
    description: "拖放、貼上或點選檔案，送出前可以檢查和移除。",
    item: "file-upload",
  },
  {
    group: "元件",
    slug: "button",
    title: "按鈕",
    description: "4 種變體，文字與圖示按鈕都是 40px 高。",
    item: "button",
  },
  {
    group: "元件",
    slug: "badge",
    title: "徽章",
    description: "狀態標籤，含成功、警告、錯誤 3 種狀態色。",
    item: "badge",
  },
  {
    group: "元件",
    slug: "input",
    title: "輸入框",
    description: "單行輸入，跟按鈕同高，可並排。",
    item: "input",
  },
  {
    group: "元件",
    slug: "textarea",
    title: "多行輸入框",
    description: "隨內容長高的多行輸入。",
    item: "textarea",
  },
  {
    group: "元件",
    slug: "label",
    title: "欄位名稱",
    description: "表單欄位的名稱，點了會聚焦對應的欄位。",
    item: "label",
  },
  {
    group: "元件",
    slug: "select",
    title: "下拉選單",
    description: "從固定選項中選一個。",
    item: "select",
  },
  {
    group: "元件",
    slug: "combobox",
    title: "下拉搜尋選單",
    description: "選項很多時可以搜尋，單選或多選都行。",
    item: "combobox",
  },
  {
    group: "元件",
    slug: "calendar",
    title: "月曆",
    description: "從月曆選一天，週一開頭。",
    item: "calendar",
  },
  {
    group: "元件",
    slug: "attachment",
    title: "附件",
    description: "一個檔案的圖示、檔名與狀態，可以移除或重試。",
    item: "attachment",
  },
  {
    group: "元件",
    slug: "checkbox",
    title: "勾選框",
    description: "圓形勾選框，可以多選。",
    item: "checkbox",
  },
  {
    group: "元件",
    slug: "switch",
    title: "開關",
    description: "立即生效的開或關。",
    item: "switch",
  },
  {
    group: "元件",
    slug: "table",
    title: "表格",
    description: "資料列表，數字欄靠右對齊。",
    item: "table",
  },
  {
    group: "元件",
    slug: "dialog",
    title: "對話框",
    description: "短表單或細節，叫出在頁面上方。",
    item: "dialog",
  },
  {
    group: "元件",
    slug: "alert-dialog",
    title: "警示對話框",
    description: "確認對話框的底層元件：標題、說明、取消與一個動作。",
    item: "alert-dialog",
  },
  {
    group: "元件",
    slug: "popover",
    title: "浮動面板",
    description: "錨定在按鈕旁的小面板。",
    item: "popover",
  },
  {
    group: "元件",
    slug: "command",
    title: "指令清單",
    description: "可搜尋的清單，下拉搜尋選單的內容。",
    item: "command",
  },
  {
    group: "元件",
    slug: "dropdown-menu",
    title: "動作選單",
    description: "一列動作，可以分組和放子選單。",
    item: "dropdown-menu",
  },
  {
    group: "元件",
    slug: "tabs",
    title: "分頁",
    description: "同一頁內切換幾個區塊。",
    item: "tabs",
  },
  {
    group: "元件",
    slug: "avatar",
    title: "頭像",
    description: "成員頭像，沒有圖時顯示名字的第一個字。",
    item: "avatar",
  },
  {
    group: "元件",
    slug: "number-ticker",
    title: "數字滾動",
    description: "整數變動時，每一位數字滾到新的值。",
    item: "number-ticker",
  },
  {
    group: "元件",
    slug: "chart",
    title: "圖表",
    description:
      "主要數列用主色，對照用灰色，有意義的數列(收入、支出)用狀態色。",
    item: "chart",
  },
  {
    group: "元件",
    slug: "tooltip",
    title: "提示",
    description: "滑過圖示時補充說明。",
    item: "tooltip",
  },
  {
    group: "元件",
    slug: "separator",
    title: "分隔線",
    description: "水平或垂直的細線。",
    item: "separator",
  },
  {
    group: "元件",
    slug: "collapsible",
    title: "摺疊區塊",
    description: "可以展開和收合的內容。",
    item: "collapsible",
  },
  {
    group: "元件",
    slug: "skeleton",
    title: "載入骨架",
    description: "資料載入前的佔位形狀。",
    item: "skeleton",
  },
  {
    group: "元件",
    slug: "sonner",
    title: "通知",
    description: "從角落跳出、幾秒後消失的通知。",
    item: "sonner",
  },
]

export const groups = ["基礎", "版面", "區塊", "元件"] as const
